### ISSUE TITLE
Archive Utility

### ISSUE THREAD

**Issue by PoisonNinja** [PoisonNinja/ToyOS#10]
This ticket will track archive porting progress.

- [x] Compression Library
- [x] Compression
- [x] Decompression

**Comment by PoisonNinja** [comment]
zlib is already ported (thanks klange!).

**Comment by PoisonNinja** [comment]
I was able to port minizip over. It runs, but I need to test it.

**Comment by PoisonNinja** [comment]
Compression is a go!

**Comment by PoisonNinja** [comment]
I think that miniunzip is the counterpart. Standby...

**Comment by PoisonNinja** [comment]
Miniunz required an updated copy of ioapi, so I had to go find one. I was able to test it successfully, and it was able to extract the necessary files!

I need to figure out how to build the binary, since I disabled a lot of things in the makefile to get it to shutup.

**Comment by PoisonNinja** [comment]
We have zipping and unzipping support!

@Saruta, can you clean up the makefile? It currently builds minizip every single time which is inefficient, and I don't know why it's doing that.

**Comment by Saruta** [comment]
Mmmmm, I will try that. But, I head that zip does not keep unix compatibility as well as tar.xz (or tar.gz).

**Comment by PoisonNinja** [comment]
libtar is good to go.
