### ISSUE TITLE
Old version of Draw! - 404

### ISSUE THREAD

**Issue by socketpair** [PoisonNinja/ToyOS#31]
https://github.com/PoisonNinja/ToyOS/wiki/Screenshots : first link `Old version of Draw!` points to missing resource

**Comment by PoisonNinja** [comment]
Hi, can you give some more information?

**Comment by socketpair** [comment]
Fixed description

**Comment by PoisonNinja** [comment]
Thanks for the report. I don't have much interest in maintaining that page, as I'm focusing on Electron, which shares a large code base with ToaruOS but with somethings written differently. I have removed the link, as it's klanges link.

If you want to see what I'm working on, check out [github.com/PoisonNinja/Electron](http://www.github.com/PoisonNinja/Electron)
